version: 0.2

phases:
  build:
    commands:
      - sudo apt-get update && sudo apt-get install -y curl build-essential libssl-dev libffi-dev python3-dev
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - npm install
      - pip install pipenv
      - pipenv lock --requirements > requirements.txt
      - pip install -r requirements.txt -t vendor
      - $(npm bin)/sls deploy
