version: 0.2

phases:
  build:
    commands:
      - sudo apt-get update && sudo apt-get install -y curl build-essential libssl-dev libffi-dev python3-dev
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - npm install
      - pip install pipenv
      - pipenv install
      - pipenv shell
      - which credstash
      - pipenv lock --requirements > requirements.txt
      - pip install -r requirements.txt -t vendor
      - export TWITTER_CONSUMER_KEY=$(credstash get twitter.consumer_key)
      - export TWITTER_CONSUMER_SECRET=$(credstash get twitter.consumer_secret)
      - export TWITTER_ACCESS_KEY=$(credstash get twitter.access_token_key)
      - export TWITTER_ACCESS_SECRET=$(credstash get twitter.access_token_secret)
      - $(npm bin)/sls deploy

