version: 0.2

phases:
  build:
    commands:
      - apt-get update && apt-get upgrade -y
      - apt-get install -y node
      - which node
      - node version
      - which npm
      - npm install
      - pip install pipenv
      - pipenv install
