version: 0.2

phases:
  build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - npm install
      - pip install pipenv
      - pipenv install
