version: 0.2

phases:
  build:
    commands:
      - apt-get update && apt-get upgrade -y
      - apt-get install -y nodejs npm
      - which nodejs
      - nodejs --version
      - which npm
      - npm install
      - pip install pipenv
      - pipenv install
